# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tokenizer.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tokenizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftokenizer.proto\x12\x0ctokenizer.v1\"-\n\x0fTokenizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\"b\n\tTokenSpec\x12\x0f\n\x07surface\x18\x01 \x01(\t\x12\x11\n\tbase_form\x18\x02 \x01(\t\x12\x0b\n\x03pos\x18\x03 \x01(\t\x12\x12\n\nspan_start\x18\x04 \x01(\x05\x12\x10\n\x08span_end\x18\x05 \x01(\x05\";\n\x10TokenizeResponse\x12\'\n\x06tokens\x18\x01 \x03(\x0b\x32\x17.tokenizer.v1.TokenSpec2]\n\x10TokenizerService\x12I\n\x08Tokenize\x12\x1d.tokenizer.v1.TokenizeRequest\x1a\x1e.tokenizer.v1.TokenizeResponseB\x1f\xaa\x02\x1cInfrastructure.Adapters.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034Infrastructure.Adapters.Grpc'
  _globals['_TOKENIZEREQUEST']._serialized_start=33
  _globals['_TOKENIZEREQUEST']._serialized_end=78
  _globals['_TOKENSPEC']._serialized_start=80
  _globals['_TOKENSPEC']._serialized_end=178
  _globals['_TOKENIZERESPONSE']._serialized_start=180
  _globals['_TOKENIZERESPONSE']._serialized_end=239
  _globals['_TOKENIZERSERVICE']._serialized_start=241
  _globals['_TOKENIZERSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
