// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CurrentKnowledgeRelease", b =>
                {
                    b.Property<short>("SingletonId")
                        .HasColumnType("smallint")
                        .HasColumnName("singleton_id");

                    b.Property<long>("ReleaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("release_id");

                    b.HasKey("SingletonId");

                    b.HasIndex("ReleaseId")
                        .IsUnique()
                        .HasDatabaseName("uq_current_knowledge_release_release");

                    b.ToTable("current_knowledge_release", null, t =>
                        {
                            t.HasCheckConstraint("chk_current_knowledge_release_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.DictionaryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalId")
                        .IsUnique()
                        .HasDatabaseName("uq_dictionary_entries_canonical_id");

                    b.ToTable("dictionary_entries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DictionarySense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.PrimitiveCollection<string[]>("PartOfSpeech")
                        .HasColumnType("text[]")
                        .HasColumnName("part_of_speech");

                    b.Property<short>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("position");

                    b.Property<string>("SenseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sense_key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("idx_dictionary_senses_entry_id");

                    b.HasIndex("EntryId", "SenseKey")
                        .IsUnique()
                        .HasDatabaseName("uq_dictionary_senses_entry_key");

                    b.ToTable("dictionary_senses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EditorialMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("decision_reason");

                    b.Property<string>("MappingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mapping_type");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<long>("SourceRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_record_id");

                    b.Property<long>("TargetResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_resource_id");

                    b.Property<string>("TargetResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_resource_type");

                    b.HasKey("Id");

                    b.HasIndex("TargetResourceType", "TargetResourceId")
                        .HasDatabaseName("idx_editorial_mappings_target");

                    b.HasIndex("SourceRecordId", "TargetResourceType", "TargetResourceId")
                        .IsUnique()
                        .HasDatabaseName("uq_editorial_mappings_source_target");

                    b.ToTable("editorial_mappings", null, t =>
                        {
                            t.HasCheckConstraint("chk_editorial_mappings_resource_type", "target_resource_type IN ('dictionary', 'kanji', 'grammar')");

                            t.HasCheckConstraint("chk_editorial_mappings_type", "mapping_type IN ('link', 'merge', 'split', 'retire')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.GrammarRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Examples")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("examples")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Formation")
                        .HasColumnType("text")
                        .HasColumnName("formation");

                    b.Property<string>("JlptLevel")
                        .HasColumnType("text")
                        .HasColumnName("jlpt_level");

                    b.Property<string>("MatcherMetadata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("matcher_metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("MeaningEn")
                        .HasColumnType("text")
                        .HasColumnName("meaning_en");

                    b.Property<string>("MeaningVi")
                        .HasColumnType("text")
                        .HasColumnName("meaning_vi");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.Property<string>("SourceMetadata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalId")
                        .IsUnique()
                        .HasDatabaseName("uq_grammar_rules_canonical_id");

                    b.HasIndex("JlptLevel")
                        .HasDatabaseName("idx_grammar_rules_jlpt")
                        .HasFilter("jlpt_level IS NOT NULL");

                    b.ToTable("grammar_rules", null, t =>
                        {
                            t.HasCheckConstraint("chk_grammar_rules_jlpt", "jlpt_level IS NULL OR jlpt_level IN ('N5', 'N4', 'N3', 'N2', 'N1')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.KanjiRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_id");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("character");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("Frequency")
                        .HasColumnType("smallint")
                        .HasColumnName("frequency");

                    b.Property<short?>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("grade");

                    b.Property<string>("HanViet")
                        .HasColumnType("text")
                        .HasColumnName("han_viet");

                    b.Property<short?>("JlptLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("jlpt_level");

                    b.Property<string>("JlptProvenance")
                        .HasColumnType("text")
                        .HasColumnName("jlpt_provenance");

                    b.PrimitiveCollection<string[]>("KunReadings")
                        .HasColumnType("text[]")
                        .HasColumnName("kun_readings");

                    b.PrimitiveCollection<string[]>("MeaningsEn")
                        .HasColumnType("text[]")
                        .HasColumnName("meanings_en");

                    b.PrimitiveCollection<string[]>("MeaningsVi")
                        .HasColumnType("text[]")
                        .HasColumnName("meanings_vi");

                    b.PrimitiveCollection<string[]>("NanoriReadings")
                        .HasColumnType("text[]")
                        .HasColumnName("nanori_readings");

                    b.PrimitiveCollection<string[]>("OnReadings")
                        .HasColumnType("text[]")
                        .HasColumnName("on_readings");

                    b.Property<short?>("RadicalNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("radical_number");

                    b.Property<string>("SourceMetadata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<short?>("StrokeCount")
                        .HasColumnType("smallint")
                        .HasColumnName("stroke_count");

                    b.Property<string>("UnicodeCodepoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unicode_codepoint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalId")
                        .IsUnique()
                        .HasDatabaseName("uq_kanji_records_canonical_id");

                    b.HasIndex("Character")
                        .IsUnique()
                        .HasDatabaseName("uq_kanji_records_character");

                    b.HasIndex("JlptLevel")
                        .HasDatabaseName("idx_kanji_records_jlpt")
                        .HasFilter("jlpt_level IS NOT NULL");

                    b.ToTable("kanji_records", null, t =>
                        {
                            t.HasCheckConstraint("chk_kanji_records_jlpt_provenance", "jlpt_provenance IS NULL OR jlpt_provenance IN ('authoritative', 'derived', 'approximate')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.KnowledgeRelease", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("uq_knowledge_releases_version");

                    b.ToTable("knowledge_releases", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KnowledgeReleaseManifest", b =>
                {
                    b.Property<long>("ReleaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("release_id");

                    b.Property<long>("ManifestId")
                        .HasColumnType("bigint")
                        .HasColumnName("manifest_id");

                    b.HasKey("ReleaseId", "ManifestId");

                    b.HasIndex("ManifestId");

                    b.ToTable("knowledge_release_manifests", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LearningReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ResourceType")
                        .HasDatabaseName("idx_learning_references_user_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("UserId", "ResourceType", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("uq_learning_references_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("learning_references", null, t =>
                        {
                            t.HasCheckConstraint("chk_learning_references_type", "resource_type IN ('dictionary', 'grammar')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.LocalizedGloss", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GlossText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gloss_text");

                    b.Property<string>("LanguageTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_tag");

                    b.Property<short>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("position");

                    b.Property<string>("ReviewStatus")
                        .HasColumnType("text")
                        .HasColumnName("review_status");

                    b.Property<long>("SenseId")
                        .HasColumnType("bigint")
                        .HasColumnName("sense_id");

                    b.Property<long?>("SourceRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_record_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("SourceRecordId");

                    b.HasIndex("SenseId", "LanguageTag")
                        .HasDatabaseName("idx_localized_glosses_sense_lang");

                    b.ToTable("localized_glosses", null, t =>
                        {
                            t.HasCheckConstraint("chk_localized_glosses_language_tag", "language_tag IN ('vi', 'en')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.PrimitiveCollection<string[]>("Info")
                        .HasColumnType("text[]")
                        .HasColumnName("info");

                    b.Property<bool>("IsCommon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_common");

                    b.Property<short?>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<string>("ReadingText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reading");

                    b.PrimitiveCollection<string[]>("RestrictedToForms")
                        .HasColumnType("text[]")
                        .HasColumnName("restricted_to_forms");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("idx_readings_entry_id");

                    b.HasIndex("ReadingText")
                        .HasDatabaseName("idx_readings_reading");

                    b.HasIndex("EntryId", "ReadingText")
                        .IsUnique()
                        .HasDatabaseName("uq_readings_entry_reading");

                    b.ToTable("readings", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResourceRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ReleaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("release_id");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("RevisionData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("revision_data")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId", "ResourceType", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("uq_resource_revisions_release_resource");

                    b.ToTable("resource_revisions", null, t =>
                        {
                            t.HasCheckConstraint("chk_resource_revisions_type", "resource_type IN ('dictionary', 'kanji', 'grammar')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.SenseApplicability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("ReadingId")
                        .HasColumnType("bigint")
                        .HasColumnName("reading_id");

                    b.Property<long>("SenseId")
                        .HasColumnType("bigint")
                        .HasColumnName("sense_id");

                    b.Property<long?>("WrittenFormId")
                        .HasColumnType("bigint")
                        .HasColumnName("written_form_id");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId");

                    b.HasIndex("WrittenFormId");

                    b.HasIndex("SenseId", "WrittenFormId", "ReadingId")
                        .IsUnique()
                        .HasDatabaseName("uq_sense_applicabilities_combo");

                    b.ToTable("sense_applicabilities", null, t =>
                        {
                            t.HasCheckConstraint("chk_sense_applicabilities_has_target", "written_form_id IS NOT NULL OR reading_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Domain.Entities.SourceManifest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attribution")
                        .HasColumnType("text")
                        .HasColumnName("attribution");

                    b.Property<string>("Checksum")
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("License")
                        .HasColumnType("text")
                        .HasColumnName("license");

                    b.Property<string>("Metadata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<int?>("RejectedCount")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_count");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_name");

                    b.Property<string>("TransformationId")
                        .HasColumnType("text")
                        .HasColumnName("transformation_id");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("text")
                        .HasColumnName("validation_result");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SourceName", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_source_manifests_name_version");

                    b.ToTable("source_manifests", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SourceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ManifestId")
                        .HasColumnType("bigint")
                        .HasColumnName("manifest_id");

                    b.Property<string>("RecordData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("record_data");

                    b.Property<string>("SourceIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_identity");

                    b.HasKey("Id");

                    b.HasIndex("SourceIdentity")
                        .HasDatabaseName("idx_source_records_identity");

                    b.HasIndex("ManifestId", "SourceIdentity")
                        .IsUnique()
                        .HasDatabaseName("uq_source_records_manifest_identity");

                    b.ToTable("source_records", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEmail")
                        .HasColumnType("text")
                        .HasColumnName("provider_email");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_user_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_external_logins_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_external_logins_provider_uid");

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WrittenForm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form");

                    b.PrimitiveCollection<string[]>("Info")
                        .HasColumnType("text[]")
                        .HasColumnName("info");

                    b.Property<bool>("IsCommon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_common");

                    b.Property<short?>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("idx_written_forms_entry_id");

                    b.HasIndex("Form")
                        .HasDatabaseName("idx_written_forms_form");

                    b.HasIndex("EntryId", "Form")
                        .IsUnique()
                        .HasDatabaseName("uq_written_forms_entry_form");

                    b.ToTable("written_forms", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CurrentKnowledgeRelease", b =>
                {
                    b.HasOne("Domain.Entities.KnowledgeRelease", "Release")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.CurrentKnowledgeRelease", "ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Domain.Entities.DictionarySense", b =>
                {
                    b.HasOne("Domain.Entities.DictionaryEntry", "Entry")
                        .WithMany("Senses")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Domain.Entities.EditorialMapping", b =>
                {
                    b.HasOne("Domain.Entities.SourceRecord", "SourceRecord")
                        .WithMany("EditorialMappings")
                        .HasForeignKey("SourceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceRecord");
                });

            modelBuilder.Entity("Domain.Entities.KnowledgeReleaseManifest", b =>
                {
                    b.HasOne("Domain.Entities.SourceManifest", "Manifest")
                        .WithMany("ReleaseManifests")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.KnowledgeRelease", "Release")
                        .WithMany("ReleaseManifests")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manifest");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Domain.Entities.LearningReference", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("LearningReferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.LocalizedGloss", b =>
                {
                    b.HasOne("Domain.Entities.DictionarySense", "Sense")
                        .WithMany("Glosses")
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SourceRecord", "SourceRecord")
                        .WithMany("Glosses")
                        .HasForeignKey("SourceRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sense");

                    b.Navigation("SourceRecord");
                });

            modelBuilder.Entity("Domain.Entities.Reading", b =>
                {
                    b.HasOne("Domain.Entities.DictionaryEntry", "Entry")
                        .WithMany("Readings")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Domain.Entities.ResourceRevision", b =>
                {
                    b.HasOne("Domain.Entities.KnowledgeRelease", "Release")
                        .WithMany("Revisions")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Domain.Entities.SenseApplicability", b =>
                {
                    b.HasOne("Domain.Entities.Reading", "ReadingEntity")
                        .WithMany("SenseApplicabilities")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.DictionarySense", "Sense")
                        .WithMany("Applicabilities")
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.WrittenForm", "WrittenForm")
                        .WithMany("SenseApplicabilities")
                        .HasForeignKey("WrittenFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReadingEntity");

                    b.Navigation("Sense");

                    b.Navigation("WrittenForm");
                });

            modelBuilder.Entity("Domain.Entities.SourceRecord", b =>
                {
                    b.HasOne("Domain.Entities.SourceManifest", "Manifest")
                        .WithMany("Records")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.WrittenForm", b =>
                {
                    b.HasOne("Domain.Entities.DictionaryEntry", "Entry")
                        .WithMany("WrittenForms")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Domain.Entities.DictionaryEntry", b =>
                {
                    b.Navigation("Readings");

                    b.Navigation("Senses");

                    b.Navigation("WrittenForms");
                });

            modelBuilder.Entity("Domain.Entities.DictionarySense", b =>
                {
                    b.Navigation("Applicabilities");

                    b.Navigation("Glosses");
                });

            modelBuilder.Entity("Domain.Entities.KnowledgeRelease", b =>
                {
                    b.Navigation("ReleaseManifests");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Domain.Entities.Reading", b =>
                {
                    b.Navigation("SenseApplicabilities");
                });

            modelBuilder.Entity("Domain.Entities.SourceManifest", b =>
                {
                    b.Navigation("Records");

                    b.Navigation("ReleaseManifests");
                });

            modelBuilder.Entity("Domain.Entities.SourceRecord", b =>
                {
                    b.Navigation("EditorialMappings");

                    b.Navigation("Glosses");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("LearningReferences");
                });

            modelBuilder.Entity("Domain.Entities.WrittenForm", b =>
                {
                    b.Navigation("SenseApplicabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
