import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  intersectRanges,
  mergeRanges,
  parseLetterOtherRanges,
  parsePropertyRanges,
  type CodePointRange,
} from "./unicodePolicyRanges.ts";

interface SourceManifestEntry {
  readonly file: string;
  readonly url: string;
  readonly sha256: string;
}

interface UnicodeManifest {
  readonly policy: {
    readonly name: string;
    readonly version: string;
    readonly unicodeVersion: string;
  };
  readonly license: {
    readonly notice: string;
    readonly termsUrl: string;
  };
  readonly sources: readonly SourceManifestEntry[];
  readonly generator: {
    readonly file: string;
    readonly algorithmVersion: string;
    readonly command: string;
  };
  generatedArtifact: {
    readonly file: string;
    sha256: string | null;
  };
}

const unicodeDirectory = dirname(fileURLToPath(import.meta.url));
const extensionDirectory = resolve(unicodeDirectory, "..");
const manifestPath = resolve(
  unicodeDirectory,
  "unicode17-sources.manifest.json",
);
const cacheDirectory = resolve(extensionDirectory, ".unicode-cache");

function sha256(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

async function loadVerifiedSource(
  source: SourceManifestEntry,
): Promise<string> {
  await mkdir(cacheDirectory, { recursive: true });
  const cachedPath = resolve(cacheDirectory, source.file);
  let content: string;

  try {
    content = await readFile(cachedPath, "utf8");
  } catch {
    const response = await fetch(source.url);
    if (!response.ok) {
      throw new Error(`Failed to download ${source.file}: HTTP ${response.status}`);
    }
    content = await response.text();
    await writeFile(cachedPath, content, "utf8");
  }

  const actualHash = sha256(content);
  if (actualHash !== source.sha256) {
    throw new Error(
      `Checksum mismatch for ${source.file}: expected ${source.sha256}, got ${actualHash}`,
    );
  }

  return content;
}

function renderGeneratedTable(
  manifest: UnicodeManifest,
  ranges: readonly CodePointRange[],
): string {
  const rows = ranges
    .map(
      ([start, end]) =>
        `  [0x${start.toString(16).toUpperCase()}, 0x${end
          .toString(16)
          .toUpperCase()}],`,
    )
    .join("\n");

  return `// Generated by ${manifest.generator.file}; do not edit manually.
// Unicode baseline: ${manifest.policy.unicodeVersion}
// Policy version: ${manifest.policy.version}

export type CodePointRange = readonly [start: number, end: number];

export const UNICODE_POLICY_VERSION = "${manifest.policy.unicodeVersion}";

export const JAPANESE_TRIGGER_RANGES: readonly CodePointRange[] = [
${rows}
] as const;
`;
}

async function generate(checkOnly: boolean): Promise<void> {
  const manifest = JSON.parse(
    await readFile(manifestPath, "utf8"),
  ) as UnicodeManifest;
  const sourceContents = new Map<string, string>();

  for (const source of manifest.sources) {
    sourceContents.set(source.file, await loadVerifiedSource(source));
  }

  const scripts = parsePropertyRanges(
    sourceContents.get("Scripts.txt") ?? "",
    new Set(["Hiragana", "Katakana"]),
  );
  const unifiedIdeographs = parsePropertyRanges(
    sourceContents.get("PropList.txt") ?? "",
    new Set(["Unified_Ideograph"]),
  );
  const compatibilityBlocks = parsePropertyRanges(
    sourceContents.get("Blocks.txt") ?? "",
    new Set([
      "CJK Compatibility Ideographs",
      "CJK Compatibility Ideographs Supplement",
    ]),
  );
  const letterOther = parseLetterOtherRanges(
    sourceContents.get("UnicodeData.txt") ?? "",
  );
  const ranges = mergeRanges([
    ...intersectRanges(scripts, letterOther),
    ...unifiedIdeographs,
    ...intersectRanges(compatibilityBlocks, letterOther),
    [0x3007, 0x3007],
  ]);
  const output = renderGeneratedTable(manifest, ranges);
  const outputPath = resolve(extensionDirectory, manifest.generatedArtifact.file);
  const outputHash = sha256(output);

  if (checkOnly) {
    const currentOutput = await readFile(outputPath, "utf8");
    if (currentOutput !== output) {
      throw new Error("Generated Unicode policy table is out of date");
    }
    if (manifest.generatedArtifact.sha256 !== outputHash) {
      throw new Error("Generated artifact checksum in manifest is out of date");
    }
    process.stdout.write(
      `Unicode policy verified: ${ranges.length} ranges, SHA-256 ${outputHash}\n`,
    );
    return;
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
  manifest.generatedArtifact.sha256 = outputHash;
  await writeFile(
    manifestPath,
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf8",
  );
  process.stdout.write(
    `Generated ${ranges.length} ranges at ${outputPath}; SHA-256 ${outputHash}\n`,
  );
}

const invokedPath = process.argv[1];
if (
  invokedPath !== undefined &&
  import.meta.url === pathToFileURL(resolve(invokedPath)).href
) {
  await generate(process.argv.includes("--check"));
}
